// Istanbul districts and neighborhoods — all 39 ilçe with official mahalle lists.
export const istanbulData = {
  "Adalar": {
    "yaka": "Anadolu",
    "mahalleler": [
      "Burgazada",
      "Heybeliada",
      "Kınalıada",
      "Maden",
      "Nizam"
    ]
  },
  "Arnavutköy": {
    "yaka": "Avrupa",
    "mahalleler": [
      "Adnan Menderes",
      "Anadolu",
      "Arnavutköy Merkez",
      "Atatürk",
      "Baklalı",
      "Balaban",
      "Boğazköy Istiklal",
      "Bolluca",
      "Boyalık",
      "Çilingir",
      "Deliklikaya",
      "Dursunköy",
      "Durusu",
      "Fatih",
      "Hacımaşlı",
      "Hadımköy",
      "Haraççı",
      "Hastane",
      "Hicret",
      "İmrahor",
      "İslambey",
      "Karaburun",
      "Karlıbayır",
      "Mareşal Fevzi Çakmak",
      "Mavigöl",
      "Mehmet Akif Ersoy",
      "Mustafa Kemal Paşa",
      "Nenehatun",
      "Ömerli",
      "Sazlıbosna",
      "Taşoluk",
      "Tayakadın",
      "Terkos",
      "Yassıören",
      "Yavuz Selim",
      "Yeniköy",
      "Yeşilbayır",
      "Yunus Emre"
    ]
  },
  "Ataşehir": {
    "yaka": "Anadolu",
    "mahalleler": [
      "Aşıkveysel",
      "Atatürk",
      "Barbaros",
      "Esatpaşa",
      "Ferhatpaşa",
      "Fetih",
      "İçerenköy",
      "İnönü",
      "Kayışdağı",
      "Küçükbakkalköy",
      "Mevlana",
      "Mimar Sinan",
      "Mustafa Kemal",
      "Örnek",
      "Yeni Çamlıca",
      "Yenisahra",
      "Yenişehir"
    ]
  },
  "Avcılar": {
    "yaka": "Avrupa",
    "mahalleler": [
      "Ambarlı",
      "Cihangir",
      "Denizköşkler",
      "Firuzköy",
      "Gümüşpala",
      "Merkez",
      "Mustafa Kemalpaşa",
      "Tahtakale",
      "Üniversite",
      "Yeşilkent"
    ]
  },
  "Bağcılar": {
    "yaka": "Avrupa",
    "mahalleler": [
      "100. Yıl",
      "15 Temmuz",
      "Bağlar",
      "Barbaros",
      "Çınar",
      "Demirkapı",
      "Fatih",
      "Fevzi Çakmak",
      "Göztepe",
      "Güneşli",
      "Hürriyet",
      "İnönü",
      "Kazım Karabekir",
      "Kemalpaşa",
      "Kirazlı",
      "Mahmutbey",
      "Merkez",
      "Sancaktepe",
      "Yavuz Selim",
      "Yenigün",
      "Yenimahalle",
      "Yıldıztepe"
    ]
  },
  "Bahçelievler": {
    "yaka": "Avrupa",
    "mahalleler": [
      "Bahçelievler",
      "Cumhuriyet",
      "Çobançeşme",
      "Fevzi Çakmak",
      "Hürriyet",
      "Kocasinan Merkez",
      "Siyavuşpaşa",
      "Soğanlı",
      "Şirinevler",
      "Yenibosna Merkez",
      "Zafer"
    ]
  },
  "Bakırköy": {
    "yaka": "Avrupa",
    "mahalleler": [
      "Ataköy 1. Kısım",
      "Ataköy 2-5-6. Kısım",
      "Ataköy 3-4-11. Kısım",
      "Ataköy 7-8-9-10. Kısım",
      "Basınköy",
      "Cevizlik",
      "Kartaltepe",
      "Osmaniye",
      "Sakızağacı",
      "Şenlikköy",
      "Yenimahalle",
      "Yeşilköy",
      "Yeşilyurt",
      "Zeytinlik",
      "Zuhuratbaba"
    ]
  },
  "Başakşehir": {
    "yaka": "Avrupa",
    "mahalleler": [
      "Altınşehir",
      "Bahçeşehir 1. Kısım",
      "Bahçeşehir 2. Kısım",
      "Başak",
      "Başakşehir",
      "Güvercintepe",
      "Kayabaşı",
      "Şahintepe",
      "Şamlar",
      "Ziya Gökalp"
    ]
  },
  "Bayrampaşa": {
    "yaka": "Avrupa",
    "mahalleler": [
      "Altıntepsi",
      "Cevatpaşa",
      "İsmet Paşa",
      "Kartaltepe",
      "Kocatepe",
      "Muratpaşa",
      "Orta",
      "Terazidere",
      "Vatan",
      "Yenidoğan",
      "Yıldırım"
    ]
  },
  "Beşiktaş": {
    "yaka": "Avrupa",
    "mahalleler": [
      "Abbasağa",
      "Akat",
      "Arnavutköy",
      "Balmumcu",
      "Bebek",
      "Cihannüma",
      "Dikilitaş",
      "Etiler",
      "Gayrettepe",
      "Konaklar",
      "Kuruçeşme",
      "Kültür",
      "Levazım",
      "Levent",
      "Mecidiye",
      "Muradiye",
      "Nisbetiye",
      "Ortaköy",
      "Sinanpaşa",
      "Türkali",
      "Ulus",
      "Vişnezade",
      "Yıldız"
    ]
  },
  "Beykoz": {
    "yaka": "Anadolu",
    "mahalleler": [
      "Acarlar",
      "Akbaba",
      "Alibahadır",
      "Anadolu Hisarı",
      "Anadolu Kavağı",
      "Anadolufeneri",
      "Baklacı",
      "Bozhane",
      "Cumhuriyet",
      "Çamlıbahçe",
      "Çengeldere",
      "Çiftlik",
      "Çiğdem",
      "Çubuklu",
      "Dereseki",
      "Elmalı",
      "Fatih",
      "Göksu",
      "Göllü",
      "Görele",
      "Göztepe",
      "Gümüşsuyu",
      "İncirköy",
      "İshaklı",
      "Kanlıca",
      "Kavacık",
      "Kaynarca",
      "Kılıçlı",
      "Mahmutşevketpaşa",
      "Merkez",
      "Ortaçeşme",
      "Öğümce",
      "Örnekköy",
      "Paşabahçe",
      "Paşamandıra",
      "Polonezköy",
      "Poyrazköy",
      "Riva",
      "Rüzgarlıbahçe",
      "Soğuksu",
      "Tokatköy",
      "Yalıköy",
      "Yavuz Selim",
      "Yeni Mahalle",
      "Zerzavatçı"
    ]
  },
  "Beylikdüzü": {
    "yaka": "Avrupa",
    "mahalleler": [
      "Adnan Kahveci",
      "Barış",
      "Büyükşehir",
      "Cumhuriyet",
      "Dereağzı",
      "Gürpınar",
      "Kavaklı",
      "Marmara",
      "Sahil",
      "Yakuplu"
    ]
  },
  "Beyoğlu": {
    "yaka": "Avrupa",
    "mahalleler": [
      "Arap Cami",
      "Asmalı Mescit",
      "Bedrettin",
      "Bereketzade",
      "Bostan",
      "Bülbül",
      "Camiikebir",
      "Cihangir",
      "Çatma Mescit",
      "Çukur",
      "Emekyemez",
      "Evliya Çelebi",
      "Fetihtepe",
      "Firuzağa",
      "Gümüşsuyu",
      "Hacıahmet",
      "Hacımimi",
      "Halıcıoğlu",
      "Hüseyinağa",
      "İstiklal",
      "Kadımehmet Efendi",
      "Kalyoncu Kulluğu",
      "Kamer Hatun",
      "Kaptanpaşa",
      "Katipmustafa Çelebi",
      "Keçeci Piri",
      "Kemankeş Karamustafapaşa",
      "Kılıçali Paşa",
      "Kocatepe",
      "Kulaksız",
      "Kuloğlu",
      "Küçük Piyale",
      "Müeyyetzade",
      "Ömer Avni",
      "Örnektepe",
      "Piripaşa",
      "Piyalepaşa",
      "Pürtelaş Hasan Efendi",
      "Sururi Mehmet Efendi",
      "Sütlüce",
      "Şahkulu",
      "Şehit Muhtar",
      "Tomtom",
      "Yahya Kahya",
      "Yenişehir"
    ]
  },
  "Büyükçekmece": {
    "yaka": "Avrupa",
    "mahalleler": [
      "19 Mayıs",
      "Ahmediye",
      "Alkent 2000",
      "Atatürk",
      "Bahçelievler",
      "Celaliye",
      "Cumhuriyet",
      "Çakmaklı",
      "Dizdariye",
      "Ekinoba",
      "Fatih",
      "Güzelce",
      "Hürriyet",
      "Kamiloba",
      "Karaağaç",
      "Kumburgaz",
      "Mimaroba",
      "Mimarsinan",
      "Murat Çesme",
      "Pınartepe",
      "Sinanoba",
      "Türkoba",
      "Ulus",
      "Yenimahalle"
    ]
  },
  "Çatalca": {
    "yaka": "Avrupa",
    "mahalleler": [
      "Akalan",
      "Atatürk",
      "Aydınlar",
      "Bahşayiş",
      "Başak",
      "Belgrat",
      "Celepköy",
      "Çakıl",
      "Çanakça",
      "Çiftlikköy",
      "Dağyenice",
      "Elbasan",
      "Fatih",
      "Ferhatpaşa",
      "Gökçeali",
      "Gümüşpınar",
      "Hallaçlı",
      "Hisarbeyli",
      "İhsaniye",
      "İnceğiz",
      "İzzettin",
      "Kabakça",
      "Kaleiçi",
      "Kalfa",
      "Karacaköy Merkez",
      "Karamandere",
      "Kestanelik",
      "Kızılcaali",
      "Muratbey Merkez",
      "Nakkaş",
      "Oklalı",
      "Ormanlı",
      "Ovayenice",
      "Örcünlü",
      "Örencik",
      "Subaşı",
      "Yalıköy",
      "Yaylacık",
      "Yazlık"
    ]
  },
  "Çekmeköy": {
    "yaka": "Anadolu",
    "mahalleler": [
      "Alemdağ",
      "Aydınlar",
      "Cumhuriyet",
      "Çamlık",
      "Çatalmeşe",
      "Ekşioğlu",
      "Güngören",
      "Hamidiye",
      "Hüseyinli",
      "Kirazlıdere",
      "Koçullu",
      "Mehmet Akif",
      "Merkez",
      "Mimar Sinan",
      "Nişantepe",
      "Ömerli",
      "Reşadiye",
      "Sırapınar",
      "Soğukpınar",
      "Sultançiftliği",
      "Taşdelen"
    ]
  },
  "Esenler": {
    "yaka": "Avrupa",
    "mahalleler": [
      "15 Temmuz",
      "Birlik",
      "Çifte Havuzlar",
      "Davutpaşa",
      "Fatih",
      "Fevzi Çakmak",
      "Havaalanı",
      "Kazım Karabekir",
      "Kemer",
      "Menderes",
      "Mimar Sinan",
      "Namık Kemal",
      "Nine Hatun",
      "Oruçreis",
      "Tuna",
      "Turgut Reis",
      "Yavuz Selim"
    ]
  },
  "Esenyurt": {
    "yaka": "Avrupa",
    "mahalleler": [
      "Akçaburgaz",
      "Akevler",
      "Akşemseddin",
      "Ardıçlı",
      "Aşık Veysel",
      "Atatürk",
      "Bağlarçeşme",
      "Balıkyolu",
      "Barbaros Hayrettin Paşa",
      "Battalgazi",
      "Cumhuriyet",
      "Çınar",
      "Esenkent",
      "Fatih",
      "Gökevler",
      "Güzelyurt",
      "Hürriyet",
      "İncirtepe",
      "İnönü",
      "İstiklal",
      "Koza",
      "Mehmet Akif Ersoy",
      "Mehterçeşme",
      "Mevlana",
      "Namık Kemal",
      "Necip Fazıl Kısakürek",
      "Orhan Gazi",
      "Osmangazi",
      "Örnek",
      "Pınar",
      "Piri Reis",
      "Saadetdere",
      "Selahaddin Eyyubi",
      "Sultaniye",
      "Süleymaniye",
      "Şehitler",
      "Talatpaşa",
      "Turgut Özal",
      "Üçevler",
      "Yenikent",
      "Yeşilkent",
      "Yunus Emre",
      "Zafer"
    ]
  },
  "Eyüpsultan": {
    "yaka": "Avrupa",
    "mahalleler": [
      "5.levent",
      "Ağaçlı",
      "Akpınar",
      "Akşemsettin",
      "Alibeyköy",
      "Çırçır",
      "Çiftalan",
      "Defterdar",
      "Düğmeciler",
      "Emniyettepe",
      "Esentepe",
      "Göktürk Merkez",
      "Güzeltepe",
      "Işıklar",
      "İhsaniye",
      "İslambey",
      "Karadolap",
      "Merkez",
      "Mimar Sinan",
      "Mithatpaşa",
      "Nişancı",
      "Odayeri",
      "Pirinççi",
      "Rami Cuma",
      "Rami Yeni",
      "Sakarya",
      "Silahtarağa",
      "Topçular",
      "Yeşilpınar"
    ]
  },
  "Fatih": {
    "yaka": "Avrupa",
    "mahalleler": [
      "Aksaray",
      "Akşemsettin",
      "Alemdar",
      "Ali Kuşçu",
      "Atikali",
      "Ayvansaray",
      "Balabanağa",
      "Balat",
      "Beyazıt",
      "Binbirdirek",
      "Cankurtaran",
      "Cerrahpaşa",
      "Cibali",
      "Demirtaş",
      "Derviş Ali",
      "Emin Sinan",
      "Hacı Kadın",
      "Haseki Sultan",
      "Hırka-i Şerif",
      "Hobyar",
      "Hoca Gıyasettin",
      "Hocapaşa",
      "İskenderpaşa",
      "Kalenderhane",
      "Karagümrük",
      "Katip Kasım",
      "Kemalpaşa",
      "Koca Mustafapaşa",
      "Küçük Ayasofya",
      "Mercan",
      "Mesihpaşa",
      "Mevlanakapı",
      "Mimar Hayrettin",
      "Mimar Kemalettin",
      "Molla Fenari",
      "Molla Gürani",
      "Molla Hüsrev",
      "Muhsine Hatun",
      "Nişanca",
      "Rüstempaşa",
      "Saraç Ishak",
      "Seyyid Ömer",
      "Silivrikapı",
      "Sultan Ahmet",
      "Sururi",
      "Süleymaniye",
      "Sümbül Efendi",
      "Şehremini",
      "Şehsuvar Bey",
      "Tahtakale",
      "Taya Hatun",
      "Topkapı",
      "Yavuz Sinan",
      "Yavuz Sultan Selim",
      "Yedikule",
      "Zeyrek"
    ]
  },
  "Gaziosmanpaşa": {
    "yaka": "Avrupa",
    "mahalleler": [
      "Bağlarbaşı",
      "Barbaros Hayrettin Paşa",
      "Fevzi Çakmak",
      "Hürriyet",
      "Karadeniz",
      "Karayolları",
      "Karlıtepe",
      "Kazım Karabekir",
      "Merkez",
      "Mevlana",
      "Pazariçi",
      "Sarıgöl",
      "Şemsipaşa",
      "Yeni Mahalle",
      "Yenidoğan",
      "Yıldıztabya"
    ]
  },
  "Güngören": {
    "yaka": "Avrupa",
    "mahalleler": [
      "Abdurrahman Nafiz Gürman",
      "Akıncılar",
      "Gençosman",
      "Güneştepe",
      "Güven",
      "Haznedar",
      "Mareşal Çakmak",
      "Mehmet Nesih Özmen",
      "Merkez",
      "Sanayi",
      "Tozkoparan"
    ]
  },
  "Kadıköy": {
    "yaka": "Anadolu",
    "mahalleler": [
      "19 Mayıs",
      "Acıbadem",
      "Bostancı",
      "Caddebostan",
      "Caferağa",
      "Dumlupınar",
      "Eğitim",
      "Erenköy",
      "Fenerbahçe",
      "Feneryolu",
      "Fikirtepe",
      "Göztepe",
      "Hasanpaşa",
      "Koşuyolu",
      "Kozyatağı",
      "Merdivenköy",
      "Osmanağa",
      "Rasimpaşa",
      "Sahrayıcedit",
      "Suadiye",
      "Zühtüpaşa"
    ]
  },
  "Kağıthane": {
    "yaka": "Avrupa",
    "mahalleler": [
      "Çağlayan",
      "Çeliktepe",
      "Emniyet Evleri",
      "Gültepe",
      "Gürsel",
      "Hamidiye",
      "Harmantepe",
      "Hürriyet",
      "Mehmet Akif Ersoy",
      "Merkez",
      "Nurtepe",
      "Ortabayır",
      "Seyrantepe",
      "Sultan Selim",
      "Şirintepe",
      "Talatpaşa",
      "Telsizler",
      "Yahya Kemal",
      "Yeşilce"
    ]
  },
  "Kartal": {
    "yaka": "Anadolu",
    "mahalleler": [
      "Atalar",
      "Cevizli",
      "Cumhuriyet",
      "Çavuşoğlu",
      "Esentepe",
      "Gümüşpınar",
      "Hürriyet",
      "Karlıktepe",
      "Kordonboyu",
      "Orhantepe",
      "Orta",
      "Petrol Iş",
      "Soğanlık Yeni",
      "Topselvi",
      "Uğur Mumcu",
      "Yakacık Çarşı",
      "Yakacık Yeni",
      "Yalı",
      "Yukarı",
      "Yunus"
    ]
  },
  "Küçükçekmece": {
    "yaka": "Avrupa",
    "mahalleler": [
      "Atakent",
      "Atatürk",
      "Beşyol",
      "Cennet",
      "Cumhuriyet",
      "Fatih",
      "Fevzi Çakmak",
      "Gültepe",
      "Halkalı Merkez",
      "İnönü",
      "İstasyon",
      "Kanarya",
      "Kartaltepe",
      "Kemalpaşa",
      "Mehmet Akif",
      "Söğütlü Çeşme",
      "Sultan Murat",
      "Tevfikbey",
      "Yarımburgaz",
      "Yeni Mahalle",
      "Yeşilova"
    ]
  },
  "Maltepe": {
    "yaka": "Anadolu",
    "mahalleler": [
      "Altayçeşme",
      "Altıntepe",
      "Aydınevler",
      "Bağlarbaşı",
      "Başıbüyük",
      "Büyükbakkalköy",
      "Cevizli",
      "Çınar",
      "Esenkent",
      "Feyzullah",
      "Fındıklı",
      "Girne",
      "Gülensu",
      "Gülsuyu",
      "İdealtepe",
      "Küçükyalı Merkez",
      "Yalı",
      "Zümrütevler"
    ]
  },
  "Pendik": {
    "yaka": "Anadolu",
    "mahalleler": [
      "Ahmet Yesevi",
      "Bahçelievler",
      "Ballıca",
      "Batı",
      "Çamçeşme",
      "Çamlık",
      "Çınardere",
      "Doğu",
      "Dumlupınar",
      "Emirli",
      "Ertuğrul Gazi",
      "Esenler",
      "Esenyalı",
      "Fatih",
      "Fevzi Çakmak",
      "Göçbeyli",
      "Güllü Bağlar",
      "Güzelyalı",
      "Harmandere",
      "Kavakpınar",
      "Kaynarca",
      "Kurna",
      "Kurtdoğmuş",
      "Kurtköy",
      "Orhangazi",
      "Orta",
      "Ramazanoğlu",
      "Sanayi",
      "Sapan Bağları",
      "Sülüntepe",
      "Şeyhli",
      "Velibaba",
      "Yayalar",
      "Yeni",
      "Yenişehir",
      "Yeşilbağlar"
    ]
  },
  "Sancaktepe": {
    "yaka": "Anadolu",
    "mahalleler": [
      "Abdurrahmangazi",
      "Akpınar",
      "Atatürk",
      "Emek",
      "Eyüp Sultan",
      "Fatih",
      "Hilal",
      "İnönü",
      "Kemal Türkler",
      "Meclis",
      "Merve",
      "Mevlana",
      "Osmangazi",
      "Paşaköy",
      "Safa",
      "Sarıgazi",
      "Veysel Karani",
      "Yenidoğan",
      "Yunus Emre"
    ]
  },
  "Sarıyer": {
    "yaka": "Avrupa",
    "mahalleler": [
      "Ayazağa",
      "Bahçeköy Kemer",
      "Bahçeköy Merkez",
      "Bahçeköy Yeni",
      "Baltalimanı",
      "Büyükdere",
      "Cumhuriyet",
      "Çamlıtepe",
      "Çayırbaşı",
      "Darüşşafaka",
      "Demirciköy",
      "Emirgan",
      "Fatih Sultan Mehmet",
      "Ferahevler",
      "Garipçe",
      "Gümüşdere",
      "Huzur",
      "İstinye",
      "Kazım Karabekir Paşa",
      "Kısırkaya",
      "Kireçburnu",
      "Kocataş",
      "Kumköy (kilyos)",
      "Maden",
      "Maslak",
      "Pınar",
      "Poligon",
      "Ptt Evleri",
      "Reşitpaşa",
      "Rumelifeneri",
      "Rumelihisarı",
      "Rumelikavağı",
      "Sarıyer Merkez",
      "Tarabya",
      "Uskumruköy",
      "Yeni",
      "Yeniköy",
      "Zekeriyaköy"
    ]
  },
  "Silivri": {
    "yaka": "Avrupa",
    "mahalleler": [
      "Akören",
      "Alibey",
      "Alipaşa",
      "Bekirli",
      "Beyciler",
      "Büyük Çavuşlu",
      "Büyük Kılıçlı",
      "Büyük Sinekli",
      "Cumhuriyet",
      "Çanta Balaban",
      "Çanta Sancaktepe",
      "Çayırdere",
      "Çeltik",
      "Danamandıra",
      "Değirmenköy Fevzipaşa",
      "Değirmenköy Ismetpaşa",
      "Fatih",
      "Fener",
      "Gazitepe",
      "Gümüşyaka",
      "Kadıköy",
      "Kavaklı Hürriyet",
      "Kavaklı Istiklal",
      "Kurfallı",
      "Küçük Kılıçlı",
      "Küçük Sinekli",
      "Mimar Sinan",
      "Ortaköy",
      "Piri Mehmet Paşa",
      "Sayalar",
      "Selimpaşa",
      "Semizkumlar",
      "Seymen",
      "Yeni",
      "Yolçatı"
    ]
  },
  "Sultanbeyli": {
    "yaka": "Anadolu",
    "mahalleler": [
      "Abdurrahmangazi",
      "Adil",
      "Ahmet Yesevi",
      "Akşemsettin",
      "Battalgazi",
      "Fatih",
      "Hamidiye",
      "Hasanpaşa",
      "Mecidiye",
      "Mehmet Akif",
      "Mimar Sinan",
      "Necip Fazıl",
      "Orhangazi",
      "Turgut Reis",
      "Yavuz Selim"
    ]
  },
  "Sultangazi": {
    "yaka": "Avrupa",
    "mahalleler": [
      "50. Yıl",
      "75. Yıl",
      "Cebeci",
      "Cumhuriyet",
      "Esentepe",
      "Eski Habipler",
      "Gazi",
      "Habibler",
      "İsmetpaşa",
      "Malkoçoğlu",
      "Sultançiftliği",
      "Uğur Mumcu",
      "Yayla",
      "Yunus Emre",
      "Zübeyde Hanım"
    ]
  },
  "Şile": {
    "yaka": "Anadolu",
    "mahalleler": [
      "Ağaçdere",
      "Ağva Merkez",
      "Ahmetli",
      "Akçakese",
      "Alacalı",
      "Avcıkoru",
      "Balibey",
      "Bıçkıdere",
      "Bozgoca",
      "Bucaklı",
      "Çataklı",
      "Çavuş",
      "Çayırbaşı",
      "Çelebi",
      "Çengilli",
      "Darlık",
      "Değirmençayırı",
      "Doğancılı",
      "Erenler",
      "Esenceli",
      "Geredeli",
      "Göçe",
      "Gökmaşlı",
      "Göksu",
      "Hacı Kasım",
      "Hacıllı",
      "Hasanlı",
      "İmrendere",
      "İmrenli",
      "İsaköy",
      "Kabakoz",
      "Kadıköy",
      "Kalem",
      "Karabeyli",
      "Karacaköy",
      "Karakiraz",
      "Karamandere",
      "Kervansaray",
      "Kızılca",
      "Korucu",
      "Kömürlük",
      "Kumbaba",
      "Kurfallı",
      "Kurna",
      "Meşrutiyet",
      "Oruçoğlu",
      "Osmanköy",
      "Ovacık",
      "Sahilköy",
      "Satmazlı",
      "Sofular",
      "Soğullu",
      "Sortullu",
      "Şuayipli",
      "Teke",
      "Ulupelit",
      "Üvezli",
      "Yaka",
      "Yaylalı",
      "Yazımanayır",
      "Yeniköy",
      "Yeşilvadi"
    ]
  },
  "Şişli": {
    "yaka": "Avrupa",
    "mahalleler": [
      "19 Mayıs",
      "Bozkurt",
      "Cumhuriyet",
      "Duatepe",
      "Ergenekon",
      "Esentepe",
      "Eskişehir",
      "Feriköy",
      "Fulya",
      "Gülbahar",
      "Halaskargazi",
      "Halide Edip Adıvar",
      "Halil Rıfat Paşa",
      "Harbiye",
      "İnönü",
      "İzzet Paşa",
      "Kaptanpaşa",
      "Kuştepe",
      "Mahmut Şevket Paşa",
      "Mecidiyeköy",
      "Merkez",
      "Meşrutiyet",
      "Paşa",
      "Teşvikiye",
      "Yayla"
    ]
  },
  "Tuzla": {
    "yaka": "Anadolu",
    "mahalleler": [
      "Akfırat",
      "Anadolu",
      "Aydınlı",
      "Aydıntepe",
      "Cami",
      "Evliya Çelebi",
      "Fatih",
      "İçmeler",
      "İstasyon",
      "Mescit",
      "Mimar Sinan",
      "Orhanlı",
      "Orta",
      "Postane",
      "Şifa",
      "Tepeören",
      "Yayla"
    ]
  },
  "Ümraniye": {
    "yaka": "Anadolu",
    "mahalleler": [
      "Adem Yavuz",
      "Altınşehir",
      "Armağanevler",
      "Aşağı Dudullu",
      "Atakent",
      "Atatürk",
      "Cemil Meriç",
      "Çakmak",
      "Çamlık",
      "Dumlupınar",
      "Elmalıkent",
      "Esenevler",
      "Esenkent",
      "Esenşehir",
      "Fatih Sultan Mehmet",
      "Finanskent",
      "Hekimbaşı",
      "Huzur",
      "Ihlamurkuyu",
      "İnkılap",
      "İstiklal",
      "Kazım Karabekir",
      "Madenler",
      "Mehmet Akif",
      "Namık Kemal",
      "Necip Fazıl",
      "Parseller",
      "Site",
      "Şerifali",
      "Tantavi",
      "Tatlısu",
      "Tepeüstü",
      "Topağacı",
      "Yamanevler",
      "Yukarı Dudullu"
    ]
  },
  "Üsküdar": {
    "yaka": "Anadolu",
    "mahalleler": [
      "Acıbadem",
      "Ahmediye",
      "Altunizade",
      "Aziz Mahmut Hüdayi",
      "Bahçelievler",
      "Barbaros",
      "Beylerbeyi",
      "Bulgurlu",
      "Burhaniye",
      "Cumhuriyet",
      "Çengelköy",
      "Ferah",
      "Güzeltepe",
      "İcadiye",
      "Kandilli",
      "Kısıklı",
      "Kirazlıtepe",
      "Kuleli",
      "Kuzguncuk",
      "Küçük Çamlıca",
      "Küçüksu",
      "Küplüce",
      "Mehmet Akif Ersoy",
      "Mimar Sinan",
      "Muratreis",
      "Salacak",
      "Selami Ali",
      "Selimiye",
      "Sultantepe",
      "Ünalan",
      "Valide-i Atik",
      "Yavuztürk",
      "Zeynep Kamil"
    ]
  },
  "Zeytinburnu": {
    "yaka": "Avrupa",
    "mahalleler": [
      "Beştelsiz",
      "Çırpıcı",
      "Gökalp",
      "Kazlıçeşme",
      "Maltepe",
      "Merkezefendi",
      "Nuripaşa",
      "Seyitnizam",
      "Sümer",
      "Telsiz",
      "Veliefendi",
      "Yenidoğan",
      "Yeşiltepe"
    ]
  }
};
